docker_gpg_key_uri: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_fingerprint_last_eight: "0EBFCD88"
docker_ce_repo_uri: "https://download.docker.com/linux/ubuntu"
docker_ubuntu_version: "xenial"
docker_repository_type: "stable"
docker_repository_architecture: "amd64"
